apiVersion: v1 
kind: Service 
metadata: 
  name: django-k8ssvc
spec:
  selector:
    app: django-k8s
  ports:
    - protocol: "TCP"
      port: 8888
      targetPort: 8000 
      nodePort: 32334
  type: NodePort 
  
